# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fibonacci.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fibonacci.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0f\x66ibonacci.proto\"!\n\x10\x46ibonacciMessage\x12\r\n\x05value\x18\x01 \x01(\x05\x32@\n\tFibonacci\x12\x33\n\tFibonacci\x12\x11.FibonacciMessage\x1a\x11.FibonacciMessage\"\x00\x62\x06proto3')
)




_FIBONACCIMESSAGE = _descriptor.Descriptor(
  name='FibonacciMessage',
  full_name='FibonacciMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='FibonacciMessage.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=52,
)

DESCRIPTOR.message_types_by_name['FibonacciMessage'] = _FIBONACCIMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FibonacciMessage = _reflection.GeneratedProtocolMessageType('FibonacciMessage', (_message.Message,), {
  'DESCRIPTOR' : _FIBONACCIMESSAGE,
  '__module__' : 'fibonacci_pb2'
  # @@protoc_insertion_point(class_scope:FibonacciMessage)
  })
_sym_db.RegisterMessage(FibonacciMessage)



_FIBONACCI = _descriptor.ServiceDescriptor(
  name='Fibonacci',
  full_name='Fibonacci',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=54,
  serialized_end=118,
  methods=[
  _descriptor.MethodDescriptor(
    name='Fibonacci',
    full_name='Fibonacci.Fibonacci',
    index=0,
    containing_service=None,
    input_type=_FIBONACCIMESSAGE,
    output_type=_FIBONACCIMESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FIBONACCI)

DESCRIPTOR.services_by_name['Fibonacci'] = _FIBONACCI

# @@protoc_insertion_point(module_scope)
